# We handle everything in asm-tester.sh
language: minimal

# Export the fold function
before_script:
  - export -f travis_fold

matrix:
  fast_finish: true
  include:

    - name: arm-largest-number-v1
      arch: amd64
      dist: bionic
      script:
        - ./run-test.sh arm-largest-number-v1

    - name: arm-largest-number-v2
      arch: amd64
      dist: bionic
      script:
        - ./run-test.sh arm-largest-number-v2

    - name: arm-largest-number-v3
      arch: amd64
      dist: bionic
      script:
        - ./run-test.sh arm-largest-number-v3

    - name: arm-redwolf-checksum
      arch: amd64
      dist: bionic
      script:
        - ./run-test.sh arm-redwolf-checksum

    - name: arm-silly-stocks
      arch: amd64
      dist: bionic
      script:
        - ./run-test.sh arm-silly-stocks

    - name: arm-taxi-me-some-numbers
      arch: amd64
      dist: bionic
      script:
        - ./run-test.sh arm-taxi-me-some-numbers

    - name: arm-utf16-endianness
      arch: amd64
      dist: bionic
      script:
        - ./run-test.sh arm-utf16-endianness

    - name: arm-speed-o-lobstahs
      arch: amd64
      dist: bionic
      script:
        - ./run-test.sh arm-speed-o-lobstahs

    - name: arm-xormul
      arch: amd64
      dist: bionic
      script:
        - ./run-test.sh arm-xormul

    - name: arm-rand-til-zero
      arch: amd64
      dist: bionic
      script:
        - ./run-test.sh arm-rand-til-zero
